sudo: required
services:
  - docker

before_install:
  - docker build -t raj1185/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true raj1185/docker-react npm run test -- --coverage

language: generic

deploy:
  - provider: elasticbeanstalk
    region: "eu-west-1"
    app: "docker-react"
    env_name: "dockerreact-env"
    bucket_name: "elasticbeanstalk-eu-west-1-116487034440"
    bucket_path: "docker-react"
    on:
      branch: master
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key:
      secure: "$AWS_SECRET_KEY"
