sudo: required
services:
  - docker

before_install:
  - docker build -t raj1185/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true raj1185/docker-react npm run test -- --coverage

language: generic